Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi

Var
   opcao,valor: real
   travar:caractere
Inicio

   escreval(" ________  ________  ___       ________  ___  ___  ___       ________  ________  ________  ________  ________     ")
   escreval("|\   ____\|\   __  \|\  \     |\   ____\|\  \|\  \|\  \     |\   __  \|\   ___ \|\   __  \|\   __  \|\   __  \    ")
   escreval("\ \  \___|\ \  \|\  \ \  \    \ \  \___|\ \  \\\  \ \  \    \ \  \|\  \ \  \_|\ \ \  \|\  \ \  \|\  \ \  \|\  \   ")
   escreval(" \ \  \    \ \   __  \ \  \    \ \  \    \ \  \\\  \ \  \    \ \   __  \ \  \ \\ \ \  \\\  \ \   _  _\ \   __  \  ")
   escreval("  \ \  \____\ \  \ \  \ \  \____\ \  \____\ \  \\\  \ \  \____\ \  \ \  \ \  \_\\ \ \  \\\  \ \  \\  \\ \  \ \  \ ")
   escreval("   \ \  \____\ \  \ \  \ \  \____\ \  \____\ \  \\\  \ \  \____\ \  \ \  \ \  \_\\ \ \  \\\  \ \  \\  \\ \  \ \  \ ")
   escreval("    \|_______|\|__|\|__|\|_______|\|_______|\|_______|\|_______|\|__|\|__|\|_______|\|_______|\|__|\|__|\|__|\|__|")
   escreval("")
   escreval("                                           Pressione ENTER para ir para o MENU!")
   leia(travar)
   limpatela




   opcao<-10
   enquanto opcao<>0 faca
      escreval
      escreval("  __  __                  ")
      escreval(" |  \/  |                 ")
      escreval(" | \  / | ___ _ __  _   _ ")
      escreval(" | |\/| |/ _ \ '_ \| | | |")
      escreval(" | |  | |  __/ | | | |_| |")
      escreval(" |_|  |_|\___|_| |_|\__,_|")
      escreval("")
      escreval("")
      escreval("Escolha qual calculo você ira fazer")
      escreval("1.Sequência de Tribonacci")
      escreval("2.Sequência de Quadrados perfeitos")
      escreval("3.Sequência Geometrica")
      escreval("")
      escreval("")
      escreval("Pressione ENTER para sair do MENU!")
      leia(opcao)

      limpatela

      se(opcao=1)entao
         escreval("==============CALCULADORA==============")
         escreval("Você escolheu Sequência de Tribonacci!")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=2)entao
         escreval("==================CALCULADORA==================")
         escreval("Você escolheu Sequência de Quadrados perfeitos!")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=3)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu Sequência Geometrica!")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=4)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=5)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=6)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=7)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=8)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

      se(opcao=9)entao
         escreval("============CALCULADORA============")
         escreval("Você escolheu !")
         escreval
         leia(travar)
         limpatela
      fimse

   fimenquanto

   escreval("                                          #                                          ")
   escreval("                                       #######                                       ")
   escreval("                                    #####+#######                                    ")
   escreval("                                 ###################                                 ")
   escreval("                             ############   ############                             ")
   escreval("                          ############         ############                          ")
   escreval("                       ###########               ###########                         ")
   escreval("                       ########        ######       ########                         ")
   escreval("                       ######        ###########        ####                         ")
   escreval("                       #########        ###########        #                         ")
   escreval("                       ############        ###########                               ")
   escreval("                          ############        ############                           ")
   escreval("                             ############        ###########                         ")
   escreval("                       ##       #############       ########                         ")
   escreval("                       #####        ###########       ######                         ")
   escreval("                       #+++####        #####        ########                         ")
   escreval("                       ####+#+####               ###########                         ")
   escreval("                          #####+#####         ###########                            ")
   escreval("                             ####+#+##### +###########                               ")
   escreval("                                ###################                                  ")
   escreval("                                   #####++######                                     ")
   escreval("                                       #####+                                        ")
   escreval("")
   escreval("")
   escreval("     #######   ###     ##    #######    #########  ########    #######  ##      #    ")
   escreval("    ##         #####   ##  ###              ##     ##         #+        ##      #    ")
   escreval("    ########   ## #### ##  ##               ##     ########  ##         #########    ")
   escreval("           ##  ##   #####  ###              ##     ##         ##        ##      #    ")
   escreval("    ########   ##     ###    #######        ##     ########    #######  ##      #    ")
Fimalgoritmo