Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/04/2026
Var
// Seção de Declarações das variáveis 
   n,i, cubo: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite um numero de elementos: ")
  leia(n)
  
  para i de 1 ate n faca
       cubo <- i * i * i
       escreval("O cubo de " , i , " é: " , cubo)
  fimpara

Fimalgoritmo